languageCode = "en-us"
title = "TWIST"
baseURL = "http://localhost:1313/"
theme = "hugo-theme-massively"
SectionPagesManu ="main"

[params.posts]
    foldername = "post"
    pagesize = "6"
    featuredpost= "true"
	

[params.settings]
    googleanalytics = "UA-113904582-3"
    disqus = "hugo-massively"
    
[menu]
    [[menu.main]]
  	name="Home"
  	identifier="home"
  	url="/"

   [[menu.main]]
  	name="More about Twist"
  	identifier="abouttwist"
  	url="/post/post1/"
	
   [[menu.main]]
  	name="More about us"
  	identifier="about"
  	url="/about/"


	
      