languageCode = "en-us"
title = "TWIST"
baseURL = "http://localhost:1313/"
theme = "hugo-theme-massively"
SectionPagesManu ="main"

[params.posts]
    foldername = "post"
    pagesize = "6"
    featuredpost= "true"
	

[params.settings]
    googleanalytics = "UA-118141496-1"
    disqus = "hugo-massively"
    
[menu]
    [[menu.main]]
  	name="Home"
  	identifier="home"
  	url="/"

   [[menu.main]]
<<<<<<< HEAD
  	name="About"
  	identifier="about"
  	url="/about/"
	weight=3
	
	[[menu.main]]
  	name="News"
  	identifier="news"
  	url="/news/"
	weight=4
	
<<<<<<< HEAD
	[[menu.main]]
=======
		[[menu.main]]
>>>>>>> massively_new_struct
  	name="Ideas & Resources"
  	identifier="ideas"
  	url="/ideas/"
	weight=5
<<<<<<< HEAD
=======
  	name="More about Twist"
  	identifier="abouttwist"
  	url="/post/post1/"
	
   [[menu.main]]
  	name="More about us"
  	identifier="about"
  	url="/about/"
>>>>>>> parent of f856c47... changes
=======

>>>>>>> massively_new_struct


	
      