SectionPagesManu = "main"
baseURL = "http://localhost:1313/"
languageCode = "en-us"
theme = "hugo-theme-massively"
title = "TWIST"

[[menu.main]]
identifier = "about"
name = "Organisers"
url = "/about/"

[[menu.main]]
identifier = "twist"
name = "Home"
url = "/"

[params.posts]
featuredpost = true
foldername = "post"
pagesize = "6"

[params.settings]
disqus = "hugo-massively"
googleanalytics = "UA-113904582-3"
