languageCode = "en-us"
title = "TWIST"
baseURL = "http://localhost:1313/"
theme = "hugo-theme-massively"

[params.posts]
    foldername = "post"
    pagesize = "6"
    featuredpost = "true"

[params.settings]
    googleanalytics = "UA-118141496-1"
    disqus = "hugo-massively"
<<<<<<< HEAD
=======
    
[menu]
    [[menu.main]]
  	name="Home"
  	identifier="home"
  	url="/"
	weight=1

   [[menu.main]]
  	name="About"
  	identifier="about"
  	url="/about/"
	weight=3
	
	[[menu.main]]
  	name="News"
  	identifier="news"
  	url="/news/"
	weight=4


	
      
>>>>>>> massively_customized
