languageCode = "en-us"
title = "TWIST"
baseURL = "http://localhost:1313/"
theme = "hugo-theme-massively"

[params.posts]
    foldername = "post"
    pagesize = "6"

[params.settings]
    googleanalytics = "UA-113904582-3"
    disqus = "hugo-massively"
    
